/**
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { PageHeader } from './PageHeader';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  PageHeader,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=24924%3A3218',
  {
    props: {
      number: figma.string('Number'),
      showLabel: figma.boolean('Show Label'),
      title: figma.string('Title'),
      label: figma.string('Label'),
      type: figma.enum('Type', {
        Icon: 'icon',
        Number: 'number',
      }),
    },
    example: (props) => <PageHeader />,
  }
);
