/**
 * Copyright IBM Corp. 2021, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
//
// File generated by build
// cspell:disable turned off for this file as it is generated from file names and other config
const defaultOrNot = (item) => item.default || item;
const config = [
  {
    label: 'About Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/aboutmodal',
    thumbnail:
      'url( ' + defaultOrNot(require('./aboutmodal--thumbnail.png')) + ')',
  },
  {
    label: 'API Key Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/apikeymodal',
    thumbnail:
      'url( ' + defaultOrNot(require('./apikeymodal--thumbnail.png')) + ')',
  },
  {
    label: 'React 16 usage',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ccs-base-react-16',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./ccs-base-react-16--thumbnail.png')) +
      ')',
  },
  {
    label: 'React 17 usage',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ccs-base-react-17',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./ccs-base-react-17--thumbnail.png')) +
      ')',
  },
  {
    label: 'codesandbox',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox',
    thumbnail:
      'url( ' + defaultOrNot(require('./codesandbox--thumbnail.png')) + ')',
  },
  {
    label: 'Canary example',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/component-flag-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./component-flag-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'Create Full Page',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/createfullpage-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./createfullpage-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'Create Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/createmodal-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./createmodal-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'Canary Side Panel',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/createsidepanel',
    thumbnail:
      'url( ' + defaultOrNot(require('./createsidepanel--thumbnail.png')) + ')',
  },
  {
    label: 'Canary Tearsheet',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/createtearsheet-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./createtearsheet-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'Canary Tearsheet Narrow',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/createtearsheetnarrow',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./createtearsheetnarrow--thumbnail.png')) +
      ')',
  },
  {
    label: 'Empty State',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/emptystate',
    thumbnail:
      'url( ' + defaultOrNot(require('./emptystate--thumbnail.png')) + ')',
  },
  {
    label: 'Prefix CSS/JS Example',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/examplecomponent-prefix-test',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./examplecomponent-prefix-test--thumbnail.png')) +
      ')',
  },
  {
    label: 'Export Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/export-modal',
    thumbnail:
      'url( ' + defaultOrNot(require('./export-modal--thumbnail.png')) + ')',
  },
  {
    label: 'Expressive Card',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/expressive-card',
    thumbnail:
      'url( ' + defaultOrNot(require('./expressive-card--thumbnail.png')) + ')',
  },
  {
    label: 'HTTP Error',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/httperror-403',
    thumbnail:
      'url( ' + defaultOrNot(require('./httperror-403--thumbnail.png')) + ')',
  },
  {
    label: 'Import Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/import-modal',
    thumbnail:
      'url( ' + defaultOrNot(require('./import-modal--thumbnail.png')) + ')',
  },
  {
    label: 'Notifications Panel',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/notificationspanel',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./notificationspanel--thumbnail.png')) +
      ')',
  },
  {
    label: 'Page Header Example',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/pageheaderexample',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./pageheaderexample--thumbnail.png')) +
      ')',
  },
  {
    label: 'Productive Card',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/productive-card',
    thumbnail:
      'url( ' + defaultOrNot(require('./productive-card--thumbnail.png')) + ')',
  },
  {
    label: 'Remove Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/remove-modal',
    thumbnail:
      'url( ' + defaultOrNot(require('./remove-modal--thumbnail.png')) + ')',
  },
  {
    label: 'Saving',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/saving',
    thumbnail: 'url( ' + defaultOrNot(require('./saving--thumbnail.png')) + ')',
  },
  {
    label: 'Status icon',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/statusicon-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./statusicon-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'Tagset',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/tagset',
    thumbnail: 'url( ' + defaultOrNot(require('./tagset--thumbnail.png')) + ')',
  },
  {
    label: 'Tearsheet',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/tearsheet-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./tearsheet-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'User Profile Image',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/userprofileimage-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./userprofileimage-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'Web Terminal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/web-terminal',
    thumbnail:
      'url( ' + defaultOrNot(require('./web-terminal--thumbnail.png')) + ')',
  },
];
export default config;
