/**
 * Copyright IBM Corp. 2021, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
//
// File generated by build
// cspell:disable turned off for this file as it is generated from file names and other config
const defaultOrNot = (item) => item.default || item;
const config = [
  {
    label: 'API Key Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/APIKeyModal',
    thumbnail:
      'url( ' + defaultOrNot(require('./APIKeyModal--thumbnail.png')) + ')',
  },
  {
    label: 'About Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/AboutModal',
    thumbnail:
      'url( ' + defaultOrNot(require('./AboutModal--thumbnail.png')) + ')',
  },
  {
    label: 'Cascade',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/Cascade',
    thumbnail:
      'url( ' + defaultOrNot(require('./Cascade--thumbnail.png')) + ')',
  },
  {
    label: 'Create Full Page',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/CreateFullPage',
    thumbnail:
      'url( ' + defaultOrNot(require('./CreateFullPage--thumbnail.png')) + ')',
  },
  {
    label: 'Create Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/CreateModal',
    thumbnail:
      'url( ' + defaultOrNot(require('./CreateModal--thumbnail.png')) + ')',
  },
  {
    label: 'Create Side Panel',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/CreateSidePanel',
    thumbnail:
      'url( ' + defaultOrNot(require('./CreateSidePanel--thumbnail.png')) + ')',
  },
  {
    label: 'Canary Tearsheet',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/CreateTearsheet',
    thumbnail:
      'url( ' + defaultOrNot(require('./CreateTearsheet--thumbnail.png')) + ')',
  },
  {
    label: 'Canary Tearsheet Narrow',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/CreateTearsheetNarrow',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./CreateTearsheetNarrow--thumbnail.png')) +
      ')',
  },
  {
    label: 'Empty State',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/EmptyStates',
    thumbnail:
      'url( ' + defaultOrNot(require('./EmptyStates--thumbnail.png')) + ')',
  },
  {
    label: 'Export Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ExportModal',
    thumbnail:
      'url( ' + defaultOrNot(require('./ExportModal--thumbnail.png')) + ')',
  },
  {
    label: 'Expressive Card',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ExpressiveCard',
    thumbnail:
      'url( ' + defaultOrNot(require('./ExpressiveCard--thumbnail.png')) + ')',
  },
  {
    label: 'HTTP Error',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/HTTPErrors',
    thumbnail:
      'url( ' + defaultOrNot(require('./HTTPErrors--thumbnail.png')) + ')',
  },
  {
    label: 'Import Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ImportModal',
    thumbnail:
      'url( ' + defaultOrNot(require('./ImportModal--thumbnail.png')) + ')',
  },
  {
    label: 'Notifications Panel',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/NotificationsPanel',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./NotificationsPanel--thumbnail.png')) +
      ')',
  },
  {
    label: 'Page Header Example',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/PageHeader',
    thumbnail:
      'url( ' + defaultOrNot(require('./PageHeader--thumbnail.png')) + ')',
  },
  {
    label: 'Productive Card',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ProductiveCard',
    thumbnail:
      'url( ' + defaultOrNot(require('./ProductiveCard--thumbnail.png')) + ')',
  },
  {
    label: 'Remove Modal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/RemoveModal',
    thumbnail:
      'url( ' + defaultOrNot(require('./RemoveModal--thumbnail.png')) + ')',
  },
  {
    label: 'Saving',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/Saving',
    thumbnail: 'url( ' + defaultOrNot(require('./Saving--thumbnail.png')) + ')',
  },
  {
    label: 'Side Panel',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/SidePanel',
    thumbnail:
      'url( ' + defaultOrNot(require('./SidePanel--thumbnail.png')) + ')',
  },
  {
    label: 'Status icon',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/StatusIcon',
    thumbnail:
      'url( ' + defaultOrNot(require('./StatusIcon--thumbnail.png')) + ')',
  },
  {
    label: 'Tagset',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/TagSet',
    thumbnail: 'url( ' + defaultOrNot(require('./TagSet--thumbnail.png')) + ')',
  },
  {
    label: 'Tearsheet',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/Tearsheet',
    thumbnail:
      'url( ' + defaultOrNot(require('./Tearsheet--thumbnail.png')) + ')',
  },
  {
    label: 'User Profile Image',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/UserProfileImage',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./UserProfileImage--thumbnail.png')) +
      ')',
  },
  {
    label: 'Web Terminal',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/WebTerminal',
    thumbnail:
      'url( ' + defaultOrNot(require('./WebTerminal--thumbnail.png')) + ')',
  },
  {
    label: 'React 16 usage',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ccs-base-react-16',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./ccs-base-react-16--thumbnail.png')) +
      ')',
  },
  {
    label: 'React 17 usage',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ccs-base-react-17',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./ccs-base-react-17--thumbnail.png')) +
      ')',
  },
  {
    label: 'codesandbox',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox',
    thumbnail:
      'url( ' + defaultOrNot(require('./codesandbox--thumbnail.png')) + ')',
  },
  {
    label: 'Canary example',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/component-flag-example',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./component-flag-example--thumbnail.png')) +
      ')',
  },
  {
    label: 'Prefix CSS/JS Example',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/prefix-example',
    thumbnail:
      'url( ' + defaultOrNot(require('./prefix-example--thumbnail.png')) + ')',
  },
];
export default config;
