/**
 * Copyright IBM Corp. 2021, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
//
// File generated by build
// cspell:disable turned off for this file as it is generated from file names and other config
const defaultOrNot = (item) => item.default || item;
const config = [
  {
    label: 'React 16 usage',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ccs-base-react-16',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./ccs-base-react-16--thumbnail.png')) +
      ')',
  },
  {
    label: 'React 17 usage',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/ccs-base-react-17',
    thumbnail:
      'url( ' +
      defaultOrNot(require('./ccs-base-react-17--thumbnail.png')) +
      ')',
  },
  {
    label: 'codesandbox',
    url: 'https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox',
    thumbnail:
      'url( ' + defaultOrNot(require('./codesandbox--thumbnail.png')) + ')',
  },
];
export default config;
