/**
 * Copyright IBM Corp. 2021, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
//
// File generated by build
// cspell:disable turned off for this file as it is generated from file names and other config
const defaultOrNot = (item) => item.default || item;
/* --- import Thumbnails */ import imageAPIKeyModal from './APIKeyModal--thumbnail.png';
import imageAboutModal from './AboutModal--thumbnail.png';
import imageCascade from './Cascade--thumbnail.png';
import imageCreateFullPage from './CreateFullPage--thumbnail.png';
import imageCreateModal from './CreateModal--thumbnail.png';
import imageCreateSidePanel from './CreateSidePanel--thumbnail.png';
import imageCreateTearsheet from './CreateTearsheet--thumbnail.png';
import imageCreateTearsheetNarrow from './CreateTearsheetNarrow--thumbnail.png';
import imageDataGrid from './DataGrid--thumbnail.png';
import imageDataSpreadsheet from './DataSpreadsheet--thumbnail.png';
import imageEditInPlace from './EditInPlace--thumbnail.png';
import imageEmptyStates from './EmptyStates--thumbnail.png';
import imageExportModal from './ExportModal--thumbnail.png';
import imageExpressiveCard from './ExpressiveCard--thumbnail.png';
import imageHTTPErrors from './HTTPErrors--thumbnail.png';
import imageImportModal from './ImportModal--thumbnail.png';
import imageNotificationsPanel from './NotificationsPanel--thumbnail.png';
import imageOptionsTile from './OptionsTile--thumbnail.png';
import imagePageHeader from './PageHeader--thumbnail.png';
import imageProductiveCard from './ProductiveCard--thumbnail.png';
import imageRemoveModal from './RemoveModal--thumbnail.png';
import imageSaving from './Saving--thumbnail.png';
import imageSidePanel from './SidePanel--thumbnail.png';
import imageStatusIcon from './StatusIcon--thumbnail.png';
import imageTagSet from './TagSet--thumbnail.png';
import imageTearsheet from './Tearsheet--thumbnail.png';
import imageUserProfileImage from './UserProfileImage--thumbnail.png';
import imageWebTerminal from './WebTerminal--thumbnail.png';
import imagePrefixExample from './prefix-example--thumbnail.png';
const config = [
  {
    label: 'API Key Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/APIKeyModal?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageAPIKeyModal}`,
  },
  {
    label: 'About Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/AboutModal?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageAboutModal}`,
  },
  {
    label: 'Cascade',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/Cascade?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageCascade}`,
  },
  {
    label: 'Create Full Page',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/CreateFullPage?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageCreateFullPage}`,
  },
  {
    label: 'Create Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/CreateModal?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageCreateModal}`,
  },
  {
    label: 'Create Side Panel',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/CreateSidePanel?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageCreateSidePanel}`,
  },
  {
    label: 'Tearsheet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/CreateTearsheet?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageCreateTearsheet}`,
  },
  {
    label: 'Tearsheet Narrow',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/CreateTearsheetNarrow?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageCreateTearsheetNarrow}`,
  },
  {
    label: 'Datagrid',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/DataGrid?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageDataGrid}`,
  },
  {
    label: 'DataSpreadsheet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/DataSpreadsheet?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageDataSpreadsheet}`,
  },
  {
    label: 'EditInPlace',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/EditInPlace?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageEditInPlace}`,
  },
  {
    label: 'Empty State',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/EmptyStates?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageEmptyStates}`,
  },
  {
    label: 'Export Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/ExportModal?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageExportModal}`,
  },
  {
    label: 'Expressive Card',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/ExpressiveCard?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageExpressiveCard}`,
  },
  {
    label: 'HTTP Error',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/HTTPErrors?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageHTTPErrors}`,
  },
  {
    label: 'Import Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/ImportModal?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageImportModal}`,
  },
  {
    label: 'Notifications Panel',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/NotificationsPanel?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageNotificationsPanel}`,
  },
  {
    label: 'OptionsTile',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/OptionsTile?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageOptionsTile}`,
  },
  {
    label: 'Page Header Example',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/PageHeader?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imagePageHeader}`,
  },
  {
    label: 'ProductiveCard',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/ProductiveCard?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageProductiveCard}`,
  },
  {
    label: 'RemoveModal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/RemoveModal?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageRemoveModal}`,
  },
  {
    label: 'Saving',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/Saving?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageSaving}`,
  },
  {
    label: 'SidePanel',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/SidePanel?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageSidePanel}`,
  },
  {
    label: 'StatusIcon',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/StatusIcon?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageStatusIcon}`,
  },
  {
    label: 'TagSet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/TagSet?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageTagSet}`,
  },
  {
    label: 'Tearsheet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/Tearsheet?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageTearsheet}`,
  },
  {
    label: 'UserProfileImage',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/UserProfileImage?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageUserProfileImage}`,
  },
  {
    label: 'WebTerminal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/WebTerminal?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imageWebTerminal}`,
  },
  {
    label: 'Prefix CSS/JS Example',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/prefix-example?file=src%2FExample%2FExample.jsx',
    thumbnail: `url(${imagePrefixExample}`,
  },
];

export default config;
