/**
 * Copyright IBM Corp. 2021, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
//
// File generated by build
// cspell:disable turned off for this file as it is generated from file names and other config
const defaultOrNot = (item) => item.default || item;
/* --- import Thumbnails */ import imageAPIKeyModal from './APIKeyModal--thumbnail.png';
import imageAboutModal from './AboutModal--thumbnail.png';
import imageBigNumbers from './BigNumbers--thumbnail.png';
import imageCascade from './Cascade--thumbnail.png';
import imageCoachmark from './Coachmark--thumbnail.png';
import imageCoachmarkBeacon from './CoachmarkBeacon--thumbnail.png';
import imageCoachmarkButton from './CoachmarkButton--thumbnail.png';
import imageCoachmarkFixed from './CoachmarkFixed--thumbnail.png';
import imageCoachmarkOverlayElement from './CoachmarkOverlayElement--thumbnail.png';
import imageCoachmarkOverlayElements from './CoachmarkOverlayElements--thumbnail.png';
import imageCoachmarkStack from './CoachmarkStack--thumbnail.png';
import imageCoachmarkWithAnimatedMedia from './CoachmarkWithAnimatedMedia--thumbnail.png';
import imageConditionBuilder from './ConditionBuilder--thumbnail.png';
import imageCreateFullPage from './CreateFullPage--thumbnail.png';
import imageCreateModal from './CreateModal--thumbnail.png';
import imageCreateSidePanel from './CreateSidePanel--thumbnail.png';
import imageCreateTearsheet from './CreateTearsheet--thumbnail.png';
import imageCreateTearsheetNarrow from './CreateTearsheetNarrow--thumbnail.png';
import imageDataSpreadsheet from './DataSpreadsheet--thumbnail.png';
import imageDatagrid from './Datagrid--thumbnail.png';
import imageDecorator from './Decorator--thumbnail.png';
import imageDelimitedList from './DelimitedList--thumbnail.png';
import imageDescriptionList from './DescriptionList--thumbnail.png';
import imageEditInPlace from './EditInPlace--thumbnail.png';
import imageEmptyStates from './EmptyStates--thumbnail.png';
import imageExportModal from './ExportModal--thumbnail.png';
import imageExpressiveCard from './ExpressiveCard--thumbnail.png';
import imageFilterPanel from './FilterPanel--thumbnail.png';
import imageFullPageError from './FullPageError--thumbnail.png';
import imageGetStartedCard from './GetStartedCard--thumbnail.png';
import imageHTTPErrors from './HTTPErrors--thumbnail.png';
import imageImportModal from './ImportModal--thumbnail.png';
import imageInlineTipWithAnimatedMedia from './InlineTipWithAnimatedMedia--thumbnail.png';
import imageInterstitialScreen from './InterstitialScreen--thumbnail.png';
import imageInterstitialScreenView from './InterstitialScreenView--thumbnail.png';
import imageInterstitialScreenWithAnimatedMedia from './InterstitialScreenWithAnimatedMedia--thumbnail.png';
import imageNav from './Nav--thumbnail.png';
import imageNotificationsPanel from './NotificationsPanel--thumbnail.png';
import imageOptionsTile from './OptionsTile--thumbnail.png';
import imagePageHeader from './PageHeader--thumbnail.png';
import imageProductiveCard from './ProductiveCard--thumbnail.png';
import imageRemoveModal from './RemoveModal--thumbnail.png';
import imageSaving from './Saving--thumbnail.png';
import imageScrollGradient from './ScrollGradient--thumbnail.png';
import imageSearchBar from './SearchBar--thumbnail.png';
import imageSidePanel from './SidePanel--thumbnail.png';
import imageStatusIcon from './StatusIcon--thumbnail.png';
import imageStatusIndicator from './StatusIndicator--thumbnail.png';
import imageStringFormatter from './StringFormatter--thumbnail.png';
import imageTagOverflow from './TagOverflow--thumbnail.png';
import imageTagSet from './TagSet--thumbnail.png';
import imageTearsheet from './Tearsheet--thumbnail.png';
import imageTruncatedList from './TruncatedList--thumbnail.png';
import imageUserAvatar from './UserAvatar--thumbnail.png';
import imageUserProfileImage from './UserProfileImage--thumbnail.png';
import imageWebTerminal from './WebTerminal--thumbnail.png';
import imagePrefixExample from './prefix-example--thumbnail.png';
import imageReact16Example from './react-16-example--thumbnail.png';
import imageReact17Example from './react-17-example--thumbnail.png';
const config = [
  {
    label: 'API Key Modal',
    directory: 'APIKeyModal',
    thumbnail: `url(${imageAPIKeyModal}`,
  },
  {
    label: 'About Modal',
    directory: 'AboutModal',
    thumbnail: `url(${imageAboutModal}`,
  },
  {
    label: 'Big-Number',
    directory: 'BigNumbers',
    thumbnail: `url(${imageBigNumbers}`,
  },
  { label: 'Cascade', directory: 'Cascade', thumbnail: `url(${imageCascade}` },
  {
    label: 'Coachmark',
    directory: 'Coachmark',
    thumbnail: `url(${imageCoachmark}`,
  },
  {
    label: 'Coachmark-Beacon',
    directory: 'CoachmarkBeacon',
    thumbnail: `url(${imageCoachmarkBeacon}`,
  },
  {
    label: 'Coachmark-Button',
    directory: 'CoachmarkButton',
    thumbnail: `url(${imageCoachmarkButton}`,
  },
  {
    label: 'Coachmark-Fixed',
    directory: 'CoachmarkFixed',
    thumbnail: `url(${imageCoachmarkFixed}`,
  },
  {
    label: 'Coachmark-Overlay-Element',
    directory: 'CoachmarkOverlayElement',
    thumbnail: `url(${imageCoachmarkOverlayElement}`,
  },
  {
    label: 'Coachmark-Overlay-Elements',
    directory: 'CoachmarkOverlayElements',
    thumbnail: `url(${imageCoachmarkOverlayElements}`,
  },
  {
    label: 'Coachmark-Stack',
    directory: 'CoachmarkStack',
    thumbnail: `url(${imageCoachmarkStack}`,
  },
  {
    label: 'Coachmark-With-Animated-Media',
    directory: 'CoachmarkWithAnimatedMedia',
    thumbnail: `url(${imageCoachmarkWithAnimatedMedia}`,
  },
  {
    label: 'Condition-Builder',
    directory: 'ConditionBuilder',
    thumbnail: `url(${imageConditionBuilder}`,
  },
  {
    label: 'Create Full Page',
    directory: 'CreateFullPage',
    thumbnail: `url(${imageCreateFullPage}`,
  },
  {
    label: 'Create Modal',
    directory: 'CreateModal',
    thumbnail: `url(${imageCreateModal}`,
  },
  {
    label: 'Create Side Panel',
    directory: 'CreateSidePanel',
    thumbnail: `url(${imageCreateSidePanel}`,
  },
  {
    label: 'Create Tearsheet',
    directory: 'CreateTearsheet',
    thumbnail: `url(${imageCreateTearsheet}`,
  },
  {
    label: 'Tearsheet Narrow',
    directory: 'CreateTearsheetNarrow',
    thumbnail: `url(${imageCreateTearsheetNarrow}`,
  },
  {
    label: 'DataSpreadsheet',
    directory: 'DataSpreadsheet',
    thumbnail: `url(${imageDataSpreadsheet}`,
  },
  {
    label: 'Datagrid',
    directory: 'Datagrid',
    thumbnail: `url(${imageDatagrid}`,
  },
  {
    label: 'Decorator',
    directory: 'Decorator',
    thumbnail: `url(${imageDecorator}`,
  },
  {
    label: 'Delimited-List',
    directory: 'DelimitedList',
    thumbnail: `url(${imageDelimitedList}`,
  },
  {
    label: 'Description-List',
    directory: 'DescriptionList',
    thumbnail: `url(${imageDescriptionList}`,
  },
  {
    label: 'EditInPlace',
    directory: 'EditInPlace',
    thumbnail: `url(${imageEditInPlace}`,
  },
  {
    label: 'Empty State',
    directory: 'EmptyStates',
    thumbnail: `url(${imageEmptyStates}`,
  },
  {
    label: 'Export Modal',
    directory: 'ExportModal',
    thumbnail: `url(${imageExportModal}`,
  },
  {
    label: 'Expressive Card',
    directory: 'ExpressiveCard',
    thumbnail: `url(${imageExpressiveCard}`,
  },
  {
    label: 'Filter-Panel',
    directory: 'FilterPanel',
    thumbnail: `url(${imageFilterPanel}`,
  },
  {
    label: 'Full-Page-Error',
    directory: 'FullPageError',
    thumbnail: `url(${imageFullPageError}`,
  },
  {
    label: 'Get-Started-Card',
    directory: 'GetStartedCard',
    thumbnail: `url(${imageGetStartedCard}`,
  },
  {
    label: 'HTTP Error',
    directory: 'HTTPErrors',
    thumbnail: `url(${imageHTTPErrors}`,
  },
  {
    label: 'Import Modal',
    directory: 'ImportModal',
    thumbnail: `url(${imageImportModal}`,
  },
  {
    label: 'InlineTip-With-Animated-Media',
    directory: 'InlineTipWithAnimatedMedia',
    thumbnail: `url(${imageInlineTipWithAnimatedMedia}`,
  },
  {
    label: 'Interstitial-Screen',
    directory: 'InterstitialScreen',
    thumbnail: `url(${imageInterstitialScreen}`,
  },
  {
    label: 'Interstitial-Screen-View',
    directory: 'InterstitialScreenView',
    thumbnail: `url(${imageInterstitialScreenView}`,
  },
  {
    label: 'Interstitial-Screen',
    directory: 'InterstitialScreenWithAnimatedMedia',
    thumbnail: `url(${imageInterstitialScreenWithAnimatedMedia}`,
  },
  { label: 'Nav', directory: 'Nav', thumbnail: `url(${imageNav}` },
  {
    label: 'Notifications Panel',
    directory: 'NotificationsPanel',
    thumbnail: `url(${imageNotificationsPanel}`,
  },
  {
    label: 'OptionsTile',
    directory: 'OptionsTile',
    thumbnail: `url(${imageOptionsTile}`,
  },
  {
    label: 'Page Header Example',
    directory: 'PageHeader',
    thumbnail: `url(${imagePageHeader}`,
  },
  {
    label: 'ProductiveCard',
    directory: 'ProductiveCard',
    thumbnail: `url(${imageProductiveCard}`,
  },
  {
    label: 'RemoveModal',
    directory: 'RemoveModal',
    thumbnail: `url(${imageRemoveModal}`,
  },
  { label: 'Saving', directory: 'Saving', thumbnail: `url(${imageSaving}` },
  {
    label: 'Scroll-Gradient',
    directory: 'ScrollGradient',
    thumbnail: `url(${imageScrollGradient}`,
  },
  {
    label: 'Search-Bar',
    directory: 'SearchBar',
    thumbnail: `url(${imageSearchBar}`,
  },
  {
    label: 'SidePanel',
    directory: 'SidePanel',
    thumbnail: `url(${imageSidePanel}`,
  },
  {
    label: 'StatusIcon',
    directory: 'StatusIcon',
    thumbnail: `url(${imageStatusIcon}`,
  },
  {
    label: 'Status-Indicator',
    directory: 'StatusIndicator',
    thumbnail: `url(${imageStatusIndicator}`,
  },
  {
    label: 'String-Formatter',
    directory: 'StringFormatter',
    thumbnail: `url(${imageStringFormatter}`,
  },
  {
    label: 'Tag-Overflow',
    directory: 'TagOverflow',
    thumbnail: `url(${imageTagOverflow}`,
  },
  { label: 'TagSet', directory: 'TagSet', thumbnail: `url(${imageTagSet}` },
  {
    label: 'Tearsheet',
    directory: 'Tearsheet',
    thumbnail: `url(${imageTearsheet}`,
  },
  {
    label: 'Truncated-List',
    directory: 'TruncatedList',
    thumbnail: `url(${imageTruncatedList}`,
  },
  {
    label: 'User-Avatar',
    directory: 'UserAvatar',
    thumbnail: `url(${imageUserAvatar}`,
  },
  {
    label: 'UserProfileImage',
    directory: 'UserProfileImage',
    thumbnail: `url(${imageUserProfileImage}`,
  },
  {
    label: 'WebTerminal',
    directory: 'WebTerminal',
    thumbnail: `url(${imageWebTerminal}`,
  },
  {
    label: 'Prefix CSS/JS Example',
    directory: 'prefix-example',
    thumbnail: `url(${imagePrefixExample}`,
  },
  {
    label: 'React 16 example',
    directory: 'react-16-example',
    thumbnail: `url(${imageReact16Example}`,
  },
  {
    label: 'React 17 example',
    directory: 'react-17-example',
    thumbnail: `url(${imageReact17Example}`,
  },
];

export default config;
