/**
 * Copyright IBM Corp. 2021, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
//
// File generated by build
// cspell:disable turned off for this file as it is generated from file names and other config
// const defaultOrNot = (item) => item.default || item;

const config = [
  {
    label: 'API Key Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/APIKeyModal/?file=src%2FExample%2FExample.jsx',
    thumbnail: './APIKeyModal--thumbnail.png',
  },
  {
    label: 'About Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/AboutModal/?file=src%2FExample%2FExample.jsx',
    thumbnail: './AboutModal--thumbnail.png',
  },
  {
    label: 'Carbon v11 template',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/Carbon-v11-template/?file=src%2FExample%2FExample.jsx',
    thumbnail: './Carbon-v11-template--thumbnail.png',
  },
  {
    label: 'Cascade',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/Cascade/?file=src%2FExample%2FExample.jsx',
    thumbnail: './Cascade--thumbnail.png',
  },
  {
    label: 'Create Full Page',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/CreateFullPage/?file=src%2FExample%2FExample.jsx',
    thumbnail: './CreateFullPage--thumbnail.png',
  },
  {
    label: 'Create Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/CreateModal/?file=src%2FExample%2FExample.jsx',
    thumbnail: './CreateModal--thumbnail.png',
  },
  {
    label: 'Create Side Panel',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/CreateSidePanel/?file=src%2FExample%2FExample.jsx',
    thumbnail: './CreateSidePanel--thumbnail.png',
  },
  {
    label: 'Tearsheet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/CreateTearsheet/?file=src%2FExample%2FExample.jsx',
    thumbnail: './CreateTearsheet--thumbnail.png',
  },
  {
    label: 'Tearsheet Narrow',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/CreateTearsheetNarrow/?file=src%2FExample%2FExample.jsx',
    thumbnail: './CreateTearsheetNarrow--thumbnail.png',
  },
  {
    label: 'DataSpreadsheet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/DataSpreadsheet/?file=src%2FExample%2FExample.jsx',
    thumbnail: './DataSpreadsheet--thumbnail.png',
  },
  {
    label: 'Datagrid',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/Datagrid/?file=src%2FExample%2FExample.jsx',
    thumbnail: './Datagrid--thumbnail.png',
  },
  {
    label: 'Empty State',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/EmptyStates/?file=src%2FExample%2FExample.jsx',
    thumbnail: './EmptyStates--thumbnail.png',
  },
  {
    label: 'Export Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/ExportModal/?file=src%2FExample%2FExample.jsx',
    thumbnail: './ExportModal--thumbnail.png',
  },
  {
    label: 'Expressive Card',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/ExpressiveCard/?file=src%2FExample%2FExample.jsx',
    thumbnail: './ExpressiveCard--thumbnail.png',
  },
  {
    label: 'HTTP Error',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/HTTPErrors/?file=src%2FExample%2FExample.jsx',
    thumbnail: './HTTPErrors--thumbnail.png',
  },
  {
    label: 'Import Modal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/ImportModal/?file=src%2FExample%2FExample.jsx',
    thumbnail: './ImportModal--thumbnail.png',
  },
  {
    label: 'Notifications Panel',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/NotificationsPanel/?file=src%2FExample%2FExample.jsx',
    thumbnail: './NotificationsPanel--thumbnail.png',
  },
  {
    label: 'OptionsTile',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/OptionsTile/?file=src%2FExample%2FExample.jsx',
    thumbnail: './OptionsTile--thumbnail.png',
  },
  {
    label: 'Page Header Example',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/PageHeader/?file=src%2FExample%2FExample.jsx',
    thumbnail: './PageHeader--thumbnail.png',
  },
  {
    label: 'ProductiveCard',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/ProductiveCard/?file=src%2FExample%2FExample.jsx',
    thumbnail: './ProductiveCard--thumbnail.png',
  },
  {
    label: 'RemoveModal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/RemoveModal/?file=src%2FExample%2FExample.jsx',
    thumbnail: './RemoveModal--thumbnail.png',
  },
  {
    label: 'Saving',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/Saving/?file=src%2FExample%2FExample.jsx',
    thumbnail: './Saving--thumbnail.png',
  },
  {
    label: 'SidePanel',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/SidePanel/?file=src%2FExample%2FExample.jsx',
    thumbnail: './SidePanel--thumbnail.png',
  },
  {
    label: 'StatusIcon',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/StatusIcon/?file=src%2FExample%2FExample.jsx',
    thumbnail: './StatusIcon--thumbnail.png',
  },
  {
    label: 'TagSet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/TagSet/?file=src%2FExample%2FExample.jsx',
    thumbnail: './TagSet--thumbnail.png',
  },
  {
    label: 'Tearsheet',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/Tearsheet/?file=src%2FExample%2FExample.jsx',
    thumbnail: './Tearsheet--thumbnail.png',
  },
  {
    label: 'UserProfileImage',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/UserProfileImage/?file=src%2FExample%2FExample.jsx',
    thumbnail: './UserProfileImage--thumbnail.png',
  },
  {
    label: 'WebTerminal',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/WebTerminal/?file=src%2FExample%2FExample.jsx',
    thumbnail: './WebTerminal--thumbnail.png',
  },
  {
    label: 'React 16 usage',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/ccs-base-react-16/?file=src%2FExample%2FExample.jsx',
    thumbnail: './ccs-base-react-16--thumbnail.png',
  },
  {
    label: 'React 17 usage',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/ccs-base-react-17/?file=src%2FExample%2FExample.jsx',
    thumbnail: './ccs-base-react-17--thumbnail.png',
  },
  {
    label: 'Prefix CSS/JS Example',
    url: 'https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/prefix-example/?file=src%2FExample%2FExample.jsx',
    thumbnail: './prefix-example--thumbnail.png',
  },
];

const getConfig = async function () {
  for (let item of config) {
    const path = await import(item.thumbnail);
    item.thumbnail = `url( "${path.default}" )`;
  }

  return config;
};
export default getConfig;
