comment:
  layout: 'condensed_header, diff, flags, components'

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

component_management:
  individual_components:
    - component_id: ibm-products-web-components # this is an identifier that should not be changed
      name: web-components # this is a display name, and can be changed freely
      paths:
        - ../packages/ibm-products
    - component_id: ibm-products # this is an identifier that should not be changed
      name: ibm-products # this is a display name, and can be changed freely
      paths:
        - ../packages/ibm-products
