# This is the config file for the github/issue-labeler action, which is used in
# the issue-labeler.yml workflow.
#
# Keys within this file are the name of the label in the repository that we want
# to add (eg: "package: styles", "severity: 1") and the value is the regular
# expression for when to apply the label. if the regular expression does not
# match, the label will not be applied.
#
# This only adds labels. Labels are not removed if the regex doesn't match. This
# is because we do not configure `sync-labels: 1` in the workflow file.
#
# When changes are made to this file, consider updating the `not-before` config
# in the workflow file to match the day you open the PR of your changes. This
# will ensure that only new issues moving forward are labelled with the contents
# of this file.
#
# @see https://github.com/marketplace/actions/regex-issue-labeler

# add needs triage label to all issues
'status: needs triage 🕵️‍♀️':
  - '/.*/'

# accessibility labels, case insensitive
'type: a11y ♿':
  - '/(a11y|accessibility)/i'
'screen-reader: JAWS':
  - '/(JAWS)/i'

# Adopter labels
# Add 'adopter: strategic-products' label if issue contains any of these
# project names. Case insensitive.
'adopter: strategic-products':
  - '/(API Connect|Turbonomic|Instana|NS1|watsonx Orchestrate|watsonx Code
    Assistant|Planning Analytics|SPSS
    Statistics|watsonx\.data|watsonx\.ai|watsonx\.governance|Maximo Application
    Suite|Environmental Intelligence Suite|Envizi ESG Suite|QRadar Log
    Insights|QRadar XDR/EDR \(ReaQta\)|Randori ASM|QRadar
    SIEM|MaaS360|Flash|Defender|Fusion|APP Connect|Apptio Cloudability|Apptio
    Targetprocess|AIOps Insights|Hybrid Cloud Mesh|Aspera|Blueworks
    Live|OpenPages|Databand\.ai|Cognos Analytics|Sterling B2B Integration
    SaaS|Sterling Order & Inventory Management|Supply Chain Intelligence
    Suite|TRIRIGA Application Suite|QRadar SOAR|Guardium Insights|Verify on
    Cloud|DataPower)/i'

# Component labels
'component: AddSelect':
  - '/(AddSelect|Add Select)/i'
'component: APIKeyModal':
  - '/(APIKeyModal|API Key Modal)/i'
'component: BigNumber':
  - '/(BigNumber|BigNumbers|Big Number| Big Numbers)/i'
'component: Card':
  - '/(Card)/i'
'component: Carousel':
  - '/(Carousel)/i'
'component: Checklist':
  - '/(Checklist)/i'
'component: Coachmark':
  - '/(Coachmark)/i'
'component: ConditionBuilder':
  - '/(ConditionBuilder|Condition Builder)/i'
'component: CreateFullPage':
  - '/(CreateFullPage)/i'
'component: CreateTearsheet':
  - '/(CreateTearsheet|Create Tearsheet|Create flows)/i'
'component: Datagrid':
  - '/(Datagrid)/i'
'component: DataSpreadsheet':
  - '/(DataSpreadsheet|Data Spreadsheet)/i'
'component: EditInPlace':
  - '/(EditInPlace|Edit In Place|InlineEdit|Inline Edit)/i'
'component: EditTearsheet':
  - '/(EditTearsheet|Edit Tearsheet|Edit flows)/i'
'component: EmptyState':
  - '/(EmptyState|Empty State)/i'
'component: FilterSummary':
  - '/(FilterSummary|Filter Summary)/i'
'component: FullPageError':
  - '/(FullPageError|Full Page Error|HTTPError|HTTP Error)/i'
'component: GuideBanner':
  - '/(GuideBanner|Guide Banner)/i'
'component: InlineTip':
  - '/(InlineTip|Inline Tip)/i'
'component: Interstitial screen':
  - '/(Interstitial screen)/i'
'component: modal':
  - '/(AboutModal|about modal|ExportModal|export modal|ImportModal|import
    modal|RemoveModal|remove modal)/i'
'component: NotificationsPanel':
  - '/(NotificationsPanel|NotificationPanel|Notifications Panel|Notification
    Panel)/i'
'component: OptionsTile':
  - '/(OptionsTile|Options Tile)/i'
'component: PageHeader':
  - '/(PageHeader|Page Header)/i'
'component: SidePanel':
  - '/(SidePanel|Side Panel)/i'
'component: StatusIcon':
  - '/(StatusIcon|Status Icon)/i'
'component: StylePicker':
  - '/(StylePicker|Style Picker)/i'
'component: TagOverflow':
  - '/(TagOverflow|Tag Overflow)/i'
'component: TagSet':
  - '/(TagSet|Tag Set)/i'
'component: Tearsheet':
  - '/(Tearsheet)/i'
'component: Toolbar':
  - '/(Toolbar|Tool bar)/i'
'component: UserAvatar':
  - '/(UserAvatar|User Avatar|UserProfileImage|User Profile Image)/i'
'component: WebTerminal':
  - '/(WebTerminal|Web Terminal)/i'

# Package labels
'package: styles':
  - '(@carbon/ibm-products-styles)'
'examples: @tanstack/table':
  - '/(tanstack)/i'

# Severity labels
'Sev 1':
  - '(Severity 1)'
'Sev 2':
  - '(Severity 2)'
'Sev 3':
  - '(Severity 3)'
'Sev 4':
  - '(Severity 4)'
