import React from "react"
import GenerateAnAPIKey from "./GenerateAnAPIKey.stories"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  GenerateAnAPIKey,
  "https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=10079%3A406771",
  {
    props: {
      type: figma.enum("Type", {
        Generate: "generate",
        Custom: "custom",
        Edit: "edit",
        "Custom edit": "custom-edit",
      }),
      stage: figma.enum("Stage", {
        Default: "default",
        Loading: "loading",
        Success: "success",
        Error: "error",
      }),
      size: figma.enum("Size", {
        Small: "small",
        "Extra small": "extra-small",
        Mobile: "mobile",
      }),
    },
    example: (props) => <GenerateAnAPIKey />,
  },
)
