# Percy config
version: 2
snapshot:
  timeout: 200
  widths:
    - 360
    - 1366
  minHeight: 1024
  percy-css: |
    * {
      animation: none !important;
      transition: none !important;
    }
storybook:
  include: ['/IBM Products/']
  exclude: [
      # Datagrid DataSpreadsheet
      '/Datagrid/*',
      '/DataSpreadsheet/',
      # PageHeader
      '/Page header/*',
      # TagSet
      '/Tag set/*',
      # MultiAddSelect
      '/MultiAddSelect: With Avatars/',
      # FullPageError
      '/FullPageError/*',
    ]
