# Percy config
version: 2
snapshot:
  widths:
    - 360
    - 1366
  minHeight: 1024
storybook:
  include: ['/IBM Products/']
  exclude: [
      # Exclude the following snapshots until randomized data is removed
      '/Datagrid/**', #excluding datagrid in percy in favour of tanstack carbon
      '/Datagrid: Batch Actions/',
      '/Datagrid: Disable Select Row/',
      '/Datagrid: With Virtualized Data/',
      '/DataSpreadsheet/',
      '/MultiAddSelect: With Avatars/',
      '/Tag set/TagSet: Five Tags/',
      '/Tag set/TagSet: Hundreds Of Tags/',
      '/Tag set/TagSet: Many Tags/',
      # Exclude the following snapshots until transitions are completed
      '/Datagrid/Filtering/Flyout: Filter flyout with initial filters/',
      '/Datagrid/Filtering/Panel: Filter panel with initial filters/',
      '/Page header/PageHeader: Page header in context/',
      '/Page header/PageHeader: Page header with actions toolbar/',
      '/Page header/PageHeader: Page header with all items, pre-collapsed/',
      '/Page header/PageHeader: Page header with long values and many items/',
      '/Page header/PageHeader: Page header with tags and navigation tabs/',
    ]
