# Percy config
version: 2
snapshot:
  timeout: 200
  widths:
    - 360
    - 1366
  minHeight: 1024
  percy-css: |
    * {
      animation: none !important;
      transition: none !important;
    }
storybook:
  include: ['/IBM Products/']
  exclude: [
      # Datagrid DataSpreadsheet
      '/Datagrid/*',
      '/DataSpreadsheet/',
      # PageHeader
      '/Page header/PageHeader: Page header in context/',
      '/Page header/PageHeader: Page header with actions toolbar/',
      '/Page header/PageHeader: Page header with all items, pre-collapsed/',
      '/Page header/PageHeader: Page header with long values and many items/',
      '/Page header/PageHeader: Page header with tags and navigation tabs/',
      '/Page header/PageHeader: Page header with tags',
      # TagSet
      '/Tag set/*',
      # MultiAddSelect
      '/MultiAddSelect: With Avatars/',
      # FullPageError
      '/FullPageError/*',
    ]
