import React from "react"
import ContentBody from "./ContentBody"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ContentBody,
  "https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=16728%3A642339",
  {
    props: {
      type: figma.enum("Type", {
        "Plain text": "plain-text",
        "Non-linear": "non-linear",
      }),
    },
    example: (props) => <ContentBody />,
  },
)
