# Netlify build and deploy settings - https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
command = "yarn lerna run build --scope=@carbon/ibm-products-web-components --include-dependencies && cd packages/ibm-products-web-components && yarn build:storybook --quiet"
publish = "packages/ibm-products-web-components/storybook-static"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"
YARN_ENABLE_GLOBAL_CACHE = "true"
YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"