import React from 'react';
import { TagSet } from './TagSet';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TagSet,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=9322%3A404195',
  {
    props: {
      // No matching props could be found for these Figma properties:
      tagArray: figma.boolean('Tag overflow', {
        true: [
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
        ],
        false: [
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
          { size: 'md', title: 'Tag', type: 'blue' },
        ],
      }),
    },
    example: ({ tagArray }) => <TagSet tags={tagArray} />,
  }
);
