import React from 'react';
import { SidePanel } from './SidePanel';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SidePanel,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=8858%3A390246',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum('Size', {
        'X-Small (256)': 'xs',
        'Small (320)': 'sm',
        'X-Large (<75%)': '2xl',
      }),
      // No matching props could be found for these Figma properties:
      // "primaryActions": figma.boolean('Primary actions'),
      // "slideOver": figma.boolean('Slide over')
    },
    example: (props) => <SidePanel open={true} size={props.size} />,
  }
);
