/**
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import FilterPanel from './FilterPanel.stories';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FilterPanel,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=12710%3A321266',
  {
    props: {
      footerButtons: figma.boolean('Footer buttons'),
      tagCount: figma.boolean('Tag count'),
      type: figma.enum('Type', {
        Accordions: 'accordions',
        Default: 'default',
        Combo: 'combo',
      }),
      categories: figma.boolean('Categories'),
    },
    example: (props) => <FilterPanel />,
  }
);
