/**
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { StoryDocsPage } from '../../global/js/utils/StoryDocsPage';

import * as stories from './Tearsheet.stories';

const DocsPage = () => (
  <StoryDocsPage
    blocks={[
      {
        story: stories.tearsheet,
      },
      {
        story: stories.withNavigation,
      },
      {
        story: stories.withInfluencer,
      },
      {
        story: stories.ReturnFocusToOpenButton,
      },
      {
        story: stories.firstElementDisabled,
      },
      {
        story: stories.firstElementReadOnly,
      },
      {
        story: stories.fullyLoaded,
      },
      {
        story: stories.stacked,
      },
      {
        story: stories.stackedMixedSizes,
      },
      {
        title: 'With presence',
        story: stories.withPresence,
        description: `
Tearsheet supports the \`enable-presence\` feature flag. When enabled, Tearsheet will not mount until it's opened and unmount when it's closed. This helps to stay in sync with the React lifecycle.

This means that:

- The DOM no longer includes Tearsheet and its children in the closed state
- Tearsheet, all of its children and their hooks will mount/unmount on open/close
- Enter & exit animations change from CSS transitions to CSS animations

Note: Only Tearsheet and its children are unmounted/mounted. Use TearsheetPresence or withTearsheetPresence to shift the presence boundary to a higher level, if necessary.
`,
        source: {
          language: 'jsx',
          code: `
// Option A: opt-in via feature flag
<FeatureFlags enablePresence>
    <Tearsheet {...args} open={open} />
</FeatureFlags>

// Option B: opt-in via tearsheet presence
<TearsheetPresence open={open}>
    <MyTearsheet {...args} />
</TearsheetPresence>

// Option C: opt-in via higher-order function
const MyTearsheet = withTearsheetPresence(({ onSubmit }) => {
  const [foo, setFoo] = useState();
  return <Tearsheet
  {...args}
  actions={[{
    kind: 'primary',
    label: 'Submit',
    onClick: () => {
      onSubmit(foo);
    }
  }]}
  />;
})

<MyTearsheet open={open} />
`,
        },
      },
      {
        title: 'With AI Label',
        description:
          'An AI Label is intended for any scenario where something is being generated by AI to reinforce AI transparency, accountability, and explainability at the UI level. A Carbon AI Label can be provided to the Tearsheet component by including an `decorator` property on it and providing the carbon AILabel component as its own custom component.<br/> The `decorator` is versatile and can also be used to render other components.',
        source: {
          language: 'html',
          code: `
<Tearsheet
  {...args}
  decorator={
    // carbon AILabel component
    <AILabel
      className="ai-label-container"
      autoAlign={false}
      align="bottom-right"
    >
      <AILabelContent>... ...</AILabelContent>
    </AILabel>
  }
>
  ...
</Tearsheet>
          `,
        },
      },
    ]}
  />
);

export default DocsPage;
