/**
 * Copyright IBM Corp. 2020, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useRef, useState } from 'react';

import { action } from '@storybook/addon-actions';

import { pkg } from '../../settings';

import {
  Button,
  Form,
  FormGroup,
  TextInput,
  AILabel,
  AILabelContent,
} from '@carbon/react';

import { TearsheetNarrow, deprecatedProps } from './TearsheetNarrow';

import {
  actionsOptions,
  actionsLabels,
  actionsMapping,
} from '../ActionSet/actions.js';

import { getDeprecatedArgTypes } from '../../global/js/utils/props-helper';
import styles from './_storybook-styles.scss?inline';

// import mdx from './Tearsheet.mdx';

export default {
  title: 'IBM Products/Components/Tearsheet/TearsheetNarrow',
  component: TearsheetNarrow,
  tags: ['autodocs'],
  parameters: { layout: 'fullscreen', styles /* docs: { page: mdx } */ },
  argTypes: {
    ...getDeprecatedArgTypes(deprecatedProps),
    actions: {
      control: { type: 'select', labels: actionsLabels },
      options: actionsOptions,
      mapping: actionsMapping(
        {
          primary: 'Create',
          secondary: 'Close',
          secondary2: 'Save',
          ghost: 'Cancel',
        },
        action
      ),
    },
    description: { control: { type: 'text' } },
    label: { control: { type: 'text' } },
    title: { control: { type: 'text' } },
    onClose: { control: { disable: true } },
    open: { control: { disable: true } },
    portalTarget: { control: { disable: true } },
    aiLabel: {
      control: {
        type: 'select',
        labels: {
          0: 'No AI Label',
          1: 'with AI Label',
        },
        default: 0,
      },
      description:
        'Optional prop that is intended for any scenerio where something is being generated by AI to reinforce AI transparency, accountibility, and explainability at the UI level.',
      options: [0, 1],
    },
    slug: {
      control: {
        type: 'select',
        labels: {
          0: 'No AI Slug',
          1: 'with AI Slug',
        },
        default: 0,
      },
      description: 'deprecated Property replaced by "aiLabel"',
      options: [0, 1],
    },
  },
};

// Test values for props.

const closeIconDescription = 'Close the tearsheet';

const description =
  'This is a description for the tearsheet, providing an opportunity to \
  describe the flow.';

const label = 'The label of the tearsheet';

const mainContent = (
  <div className="tearsheet-stories__narrow-content-block">
    <Form>
      <p>Main content</p>
      <FormGroup
        legendId="tearsheetNarrow-form-group"
        legendText="FormGroup Legend"
      >
        <TextInput id="tss-ft1" labelText="Enter an important value here" />
      </FormGroup>
    </Form>
  </div>
);

const title = 'Title of the tearsheet';

const sampleAILabel = (
  <AILabel className="aiLabel-container" size="xs">
    <AILabelContent>
      <div>
        <p className="secondary">AI Explained</p>
        <h1>84%</h1>
        <p className="secondary bold">Confidence score</p>
        <p className="secondary">
          This is not really Lorem Ipsum but the spell checker did not like the
          previous text with it&apos;s non-words which is why this unwieldy
          sentence, should one choose to call it that, here.
        </p>
        <hr />
        <p className="secondary">Model type</p>
        <p className="bold">Foundation model</p>
      </div>
    </AILabelContent>
  </AILabel>
);

// Template.
// eslint-disable-next-line react/prop-types
const Template = ({ actions, aiLabel, slug, ...args }) => {
  const [open, setOpen] = useState(false);
  const ref = useRef();

  const wiredActions = Array.prototype.map.call(actions, (action) => {
    if (action.label === 'Cancel') {
      const previousClick = action.onClick;
      return {
        ...action,
        onClick: (evt) => {
          setOpen(false);
          previousClick(evt);
        },
      };
    }
    return action;
  });

  return (
    <>
      <style>{`.${pkg.prefix}--tearsheet { opacity: 0 }`};</style>
      <Button onClick={() => setOpen(true)}>Open Tearsheet</Button>
      <div ref={ref}>
        <TearsheetNarrow
          {...args}
          actions={wiredActions}
          open={open}
          onClose={() => setOpen(false)}
          aiLabel={aiLabel && sampleAILabel}
          slug={slug && sampleAILabel}
        >
          {mainContent}
        </TearsheetNarrow>
      </div>
    </>
  );
};

// eslint-disable-next-line react/prop-types
const StackedTemplate = ({ actions, aiLabel, slug, ...args }) => {
  const [open1, setOpen1] = useState(false);
  const [open2, setOpen2] = useState(false);
  const [open3, setOpen3] = useState(false);
  const ref = useRef();

  const wiredActions1 = Array.prototype.map.call(actions, (action) => {
    if (action.label === 'Cancel') {
      const previousClick = action.onClick;
      return {
        ...action,
        onClick: (evt) => {
          setOpen1(false);
          previousClick(evt);
        },
      };
    }
    return action;
  });

  const wiredActions2 = Array.prototype.map.call(actions, (action) => {
    if (action.label === 'Cancel') {
      const previousClick = action.onClick;
      return {
        ...action,
        onClick: (evt) => {
          setOpen2(false);
          previousClick(evt);
        },
      };
    }
    return action;
  });

  const wiredActions3 = Array.prototype.map.call(actions, (action) => {
    if (action.label === 'Cancel') {
      const previousClick = action.onClick;
      return {
        ...action,
        onClick: (evt) => {
          setOpen3(false);
          previousClick(evt);
        },
      };
    }
    return action;
  });

  return (
    <>
      <style>{`.${pkg.prefix}--tearsheet { opacity: 0 }`};</style>
      <div style={{ height: '3rem' }} data-reserve-space="for toggle buttons" />
      <div
        style={{
          display: 'flex',
          position: 'fixed',
          top: 0,
          left: 0,
          zIndex: 10000,
        }}
      >
        <Button onClick={() => setOpen1(!open1)}>Toggle #1</Button>
        <Button onClick={() => setOpen2(!open2)}>Toggle #2</Button>
        <Button onClick={() => setOpen3(!open3)}>Toggle #3</Button>
      </div>
      <div ref={ref}>
        <TearsheetNarrow
          {...args}
          actions={wiredActions1}
          title="Tearsheet #1"
          open={open1}
          onClose={() => setOpen1(false)}
          aiLabel={aiLabel && sampleAILabel}
          slug={slug && sampleAILabel}
        >
          <div className="tearsheet-stories__narrow-content-block">
            Main content 1
          </div>
        </TearsheetNarrow>
        <TearsheetNarrow
          {...args}
          actions={wiredActions2}
          title="Tearsheet #2"
          open={open2}
          onClose={() => setOpen2(false)}
          aiLabel={aiLabel && sampleAILabel}
          slug={slug && sampleAILabel}
          selectorPrimaryFocus="#main-content"
        >
          <div className="tearsheet-stories__narrow-content-block">
            Main content 2
          </div>
        </TearsheetNarrow>
        <TearsheetNarrow
          {...args}
          actions={wiredActions3}
          title="Tearsheet #3"
          open={open3}
          onClose={() => setOpen3(false)}
          aiLabel={aiLabel && sampleAILabel}
          slug={slug && sampleAILabel}
          selectorPrimaryFocus="#main-content"
        >
          <div className="tearsheet-stories__narrow-content-block">
            Main content 3
          </div>
        </TearsheetNarrow>
      </div>
    </>
  );
};

// Stories
export const tearsheetNarrow = Template.bind({});
tearsheetNarrow.storyName = 'Narrow tearsheet';
tearsheetNarrow.args = {
  closeIconDescription,
  description,
  onClose: action('onClose called'),
  title,
  actions: 7,
};

export const fullyLoaded = Template.bind({});
fullyLoaded.storyName = 'Narrow tearsheet with all header items';
fullyLoaded.args = {
  closeIconDescription,
  description,
  hasCloseIcon: true,
  label,
  onClose: action('onClose called'),
  title,
  actions: 0,
  aiLabel: 1,
};

export const stacked = StackedTemplate.bind({});
stacked.storyName = 'Stacking narrow tearsheets';
stacked.args = {
  closeIconDescription,
  description,
  height: 'lower',
  label,
  actions: 7,
};
