import React from "react"
import { Guidebanner } from "./Guidebanner"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Guidebanner,
  "https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=16728%3A642275",
  {
    props: {
      headerText: figma.string("Header text"),
      type: figma.enum("Type", {
        Collapsable: "collapsable",
        "Not collapsable": "not-collapsable",
      }),
      expanded: figma.boolean("Expanded"),
      pagination: figma.boolean("Pagination"),
    },
    example: (props) => <Guidebanner />,
  },
)
