/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { GuidebannerElement } from './GuidebannerElement';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  GuidebannerElement,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=16728%3A642201',
  {
    props: {
      description: figma.enum('Content', {
        'Plain text': 'plain-text',
        'Non linear': 'non-linear',
      }),
      // button: figma.enum('CTA', {
      //   "Tertiary button": "tertiary-button",
      //   "Ghost button": "ghost-button",
      //   "Link": "link",
      //   "No CTA": "no-cta"
      // })
      button: figma.children('_Guide banner button'),
    },
    example: (props) => (
      <GuidebannerElement
        description={props.description}
        button={props.button}
      />
    ),
  }
);
