import React from "react"
import { GuidebannerElementButton } from "./GuidebannerElementButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  GuidebannerElementButton,
  "https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=17606%3A27272",
  {
    props: {
      state: figma.enum("State", {
        Enabled: "enabled",
        Hover: "hover",
      }),
    },
    example: (props) => <GuidebannerElementButton />,
  },
)
