/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React from 'react';
import { NotificationsPanel } from './NotificationsPanel';
import data from './NotificationsPanel_data';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

const notificationsData = data.slice(0, 5);

figma.connect(
  NotificationsPanel,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf?node-id=10574%3A240266',
  {
    props: {
      title: figma.textContent('Notifications'),
      emptyStateLabel: figma.textContent('You do not have any notifications'),
      dismissAllLabel: figma.textContent('Dismiss all'),
      doNotDisturbLabel: figma.textContent('Do not disturb'),
    },
    example: (props) => (
      <NotificationsPanel
        open={true}
        data={notificationsData}
        {...props}
        dateTimeLocale="en-US"
      />
    ),
  }
);
