import React from 'react';
import { InlineTip } from './InlineTip';
import { InlineTipButton } from './InlineTipButton';
import { InlineTipLink } from './InlineTipLink';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  InlineTip,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=16728%3A642364',
  {
    props: {
      narrow: figma.enum('Type', {
        Wide: false,
        Narrow: true,
      }),
      collapsible: figma.boolean('Expandable'),

      contentInstance: figma.nestedProps('_Content', {
        title: figma.textContent('"Title"'),
        body: figma.enum('Type', {
          'Plain text': figma.textContent('"Message"'),
          'Non-linear': figma.children('"Non-linear reading"'),
        }),
      }),

      expanded: figma.enum('Expanded', {
        True: 'true',
        False: 'false',
        'N/A': 'n-a',
      }),

      renderMedia: figma.enum('Image', {
        True: () => <img alt="" src="./path/to/image.png" />,
        False: undefined,
        'N/A': undefined,
      }),

      contentCta: figma.nestedProps('_Content CTA', {
        action: figma.enum('CTA', {
          'Ghost button': <InlineTipButton>Button</InlineTipButton>,
          Link: <InlineTipLink>Link</InlineTipLink>,
        }),
      }),

      tertiary: figma.boolean('Tertiary'),
    },
    //
    example: (props) => (
      <InlineTip
        collapseButtonLabel="Read less"
        expandButtonLabel="Read more"
        renderMedia={props.renderMedia}
        action={props.contentCta.action}
        narrow={props.narrow}
        title={props.contentInstance.title}
        collapsible={props.collapsible}
      >
        {props.contentInstance.body}
      </InlineTip>
    ),
  }
);
