import React from "react"
import { CardFooter } from "./CardFooter"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardFooter,
  "https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=24931%3A1316",
  {
    props: {
      duration: figma.string("Duration"),
      level: figma.string("Level"),
      showDuration: figma.boolean("Show Duration"),
      showLevel: figma.boolean("Show Level"),
      metadata: figma.boolean("Metadata"),
    },
    example: (props) => <CardFooter />,
  },
)
